# Generated by Django 3.1.12 on 2022-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210927_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ctatext',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='media',
            name='ctaurl',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='media',
            name='photo_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='media',
            name='site',
            field=models.CharField(default='', max_length=300),
        ),
    ]
